import { createHash } from "node:crypto";
import { cpSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, relative, resolve } from "node:path";
import { excludedAssets, rewriteCssAssets, rewriteHtmlAssets } from "./delivery-paths.mjs";

const root = resolve(import.meta.dirname, "..");
const output = resolve(root, "dist");
const marker = join(output, ".verde-generated");

// Refuse to erase an unrelated directory: only this generated output is disposable.
if (dirname(output) !== root || basename(output) !== "dist") throw new Error("Unsafe build output path.");
if (existsSync(output)) {
    const outputStat = lstatSync(output);
    if (outputStat.isSymbolicLink() || !outputStat.isDirectory()) throw new Error("Unsafe build output path: dist/ must be a real directory.");
    if (existsSync(marker)) {
        rmSync(output, { recursive: true });
    } else if (readdirSync(output).length > 0) {
        throw new Error("dist/ already exists without the Verde build marker; move it aside before building.");
    }
    // Hosting providers may create an empty output directory before invoking the build.
    // Reuse that empty directory; never erase unmarked contents.
}
mkdirSync(output, { recursive: true });
writeFileSync(marker, "Generated by scripts/build-site.mjs.\n");

const fingerprinted = {};
const sourceAssets = new Map();
const normalize = (path) => path.replaceAll("\\", "/");

function collectAssets(directory) {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
        const source = join(directory, entry.name);
        if (entry.isDirectory()) {
            collectAssets(source);
            continue;
        }
        const sourcePath = normalize(relative(root, source));
        if (excludedAssets.has(sourcePath)) continue;
        sourceAssets.set(sourcePath, readFileSync(source));
    }
}

collectAssets(join(root, "assets"));

function fingerprint(path, bytes) {
    const hash = createHash("sha256").update(bytes).digest("hex").slice(0, 12);
    fingerprinted[path] = path.replace(/(\.[^.]+)$/, `.${hash}$1`);
}

// Font names must be resolved first so their consuming stylesheet changes too.
for (const [path, bytes] of sourceAssets) {
    if ([".js", ".woff2"].includes(extname(path))) fingerprint(path, bytes);
}
for (const [path, bytes] of sourceAssets) {
    if (!path.endsWith(".css")) continue;
    const rewritten = Buffer.from(rewriteCssAssets(bytes.toString("utf8"), path, fingerprinted));
    sourceAssets.set(path, rewritten);
    fingerprint(path, rewritten);
}
for (const [path, bytes] of sourceAssets) {
    const target = join(output, fingerprinted[path] || path);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, bytes);
}

const pages = readdirSync(root).filter((file) => file.endsWith(".html")).sort();
for (const page of pages) {
    const source = rewriteHtmlAssets(readFileSync(join(root, page), "utf8"), fingerprinted);
    writeFileSync(join(output, page), source);
}
for (const file of ["robots.txt", "sitemap.xml", "site.webmanifest"]) cpSync(join(root, file), join(output, file));
writeFileSync(join(output, "asset-manifest.json"), `${JSON.stringify(fingerprinted, null, 2)}\n`);

const cssSize = statSync(join(root, "assets/css/verde-tailwind.css")).size;
console.log(`Built ${pages.length} static pages; ${Object.keys(fingerprinted).length} fingerprinted CSS/JS/font assets.`);
console.log(`Tailwind compiled ahead of time: ${cssSize.toLocaleString()} bytes (no browser compiler).`);
